### ISSUE TITLE
error running count 

### ISSUE THREAD

**Issue by sciai-ai** [wyang17/SQuIRE#32]
Hi, I get the following error when running squire count

squire Count -r 76 -b hg19 -p 16 -v -e 10

Warning: gene "CDY1" (on chrY) has reference transcripts on both strands?
Warning: gene "TTTY3" (on chrY) has reference transcripts on both strands?
Warning: gene "TTTY3B" (on chrY) has reference transcripts on both strands?
Creating temporary files2019-06-27 08:42:57.385653

Creating unique and multiple alignment bedfiles 2019-06-27 08:42:57.385925

Identifying properly paired reads 2019-06-27 08:42:57.385953

Intersecting bam files with TE bedfile 2019-06-27 08:43:39.311783

Splitting into read1 and read 2 2019-06-27 08:44:24.749062

Combining adjacent TEs with same read alignment 2019-06-27 08:44:26.709173

Getting genomic coordinates of read2019-06-27 08:44:49.983114

Identifying and labeling unique and multi reads2019-06-27 08:44:57.855092

Matching paired-end mates and merging coordinates2019-06-27 08:45:03.586699

join: multi-character tab ‘$\\t’
Traceback (most recent call last):
  File "/mnt/RNA-SEQ/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/mnt/RNA-SEQ/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/mnt/RNA-SEQ/SQuIRE/squire/Count.py", line 1743, in main
    match_reads(paired_tempfile1_ulabeled,paired_tempfile2_ulabeled,strandedness,paired_matched_tempfile,paired_unmatched1, paired_unmatched2,debug) #match pairs between paired files
  File "/mnt/RNA-SEQ/SQuIRE/squire/Count.py", line 494, in match_reads
    sp.check_call(["/bin/sh","-c",joincommand])
  File "/mnt/RNA-SEQ/miniconda3/envs/squire/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', "join -j 12 -t $'\\t' -o 1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,2.10 /mnt/RNA-SEQ/MCF-7/squire_count/CTRL_1.fastq_paired_ulabeled_1.tmpx3ba1x_newread_v1 /mnt/RNA-SEQ/MCF-7/squire_count/CTRL_1.fastq_paired_ulabeled_2.tmpke3IRJ_newread_v1 > /mnt/RNA-SEQ/MCF-7/squire_count/CTRL_1.fastq_paired_matched.tmpeea9kD_10k_v1"]' returned non-zero exit status 1

**Comment by dborgesr** [comment]
Hello,

Unfortunately, yup, same here getting the above error:

join: multi-character tab '$\\t'
Traceback (most recent call last):
  File "/root/miniconda2/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/SQuIRE/squire/Count.py", line 1743, in main
    match_reads(paired_tempfile1_ulabeled,paired_tempfile2_ulabeled,strandedness,paired_matched_tempfile,paired_unmatched1, paired_unmatched2,debug) #match pairs between paired files
  File "/SQuIRE/squire/Count.py", line 494, in match_reads
    sp.check_call(["/bin/sh","-c",joincommand])
  File "/root/miniconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', "join -j 12 -t $'\\t' -o 1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,2.10 /input_dir/squire_files/squire_count/test_sample_paired_ulabeled_1.tmpn4PloM_newread_v1 /input_dir/squire_files/squire_count/test_sample_paired_ulabeled_2.tmpSAvM6v_newread_v1 > /input_dir/squire_files/squire_count/test_sample_paired_matched.tmp7J6W20_10k_v1"]' returned non-zero exit status 1

I think the problem is coming from different versions of join

**Comment by SamMondal** [comment]
Hi, I also have the same issue with squire Count. It fails at the "join" step. Could you please help finding a way out?
Thanks!

**Comment by mariuswalter** [comment]
I had the same issue (I think) a while ago and we manage to fix it,
see here: https://github.com/wyang17/SQuIRE/issues/19#issuecomment-467775974

I thought it was fixed tho?

**Comment by SamMondal** [comment]
Thanks @mariuswalter! Yes, after playing with all possible combinations of $, ', \, and t - I found a similar way around using `echo`!

**Comment by alfonsosaera** [comment]
Hi @SamMondal , I am having similar issues. Could you share your solution? Thanks!

**Comment by fernandogs97** [comment]
Hello all! I have benn trying to find a solution to the same problem, but after doing all the solutions mentioned in this (and in the related post) I am still having the same error. Can someone help me?
`bash --version`
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

Join --version
join (GNU coreutils) 8.28

**Comment by CWYuan08** [comment]
@fernandogs97 Hi Did you manage to resolve this? Thank you very much!
